name = "airtable-form-handler"
main = "src/index.ts"
compatibility_date = "2022-07-27"
routes = [
	{ pattern = "api.jeremynguyen.dev", custom_domain = true }
]

[vars]
AIRTABLE_BASE_ID = "appi4ZoizOgWqUPHa"
AIRTABLE_TABLE_NAME = "Form Submissions"